# Generated by Django 5.2.12 on 2026-03-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_retailer_alter_category_slug_alter_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.retailer",
            ),
        ),
    ]
