# Generated by Django 5.2.12 on 2026-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_retailer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_images",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
