# Generated by Django 5.2.12 on 2026-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_currency_product_sale_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retailer_name", models.CharField(max_length=100)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("loaded", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("total_found", models.IntegerField(default=0)),
                ("status", models.CharField(default="success", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "uploaded_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
