# Generated by Django 5.2.12 on 2026-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_uploadlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="feed_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="retailer",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
