# Generated by Django 5.2.12 on 2026-03-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_retailer_feed_url_retailer_last_fetched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent")},
        ),
    ]
