# Generated by Django 5.2.12 on 2026-03-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0009_category_level_category_parent_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_sku_ca0cdc_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_categor_47b724_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="₹", max_length=10),
        ),
    ]
