# Generated by Django 5.2.12 on 2026-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_categories_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=100)),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("retailer_name", models.CharField(db_index=True, max_length=100)),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "old_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("price_up", "Price Increased"),
                            ("price_down", "Price Decreased"),
                            ("sale_added", "Sale Price Added"),
                            ("sale_removed", "Sale Price Removed"),
                            ("sale_changed", "Sale Price Changed"),
                            ("new_product", "New Product"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="₹", max_length=10)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_sku_ca0cdc_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_categor_47b724_idx",
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["retailer_name", "detected_at"],
                name="products_pr_retaile_ac086f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["sku", "detected_at"], name="products_pr_sku_2deab6_idx"
            ),
        ),
    ]
