# Generated by Django 5.2.12 on 2026-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_pricehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadlog",
            name="duration_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
